name: gBiome
main: com.egroen.bukkit.gbiome.GBiome
version: 0.1
description: Lets you change level-biomes using world-edit selections.
depend: [WorldEdit]

commands:
  gbiome:
    aliases: gb
    permission: gbiome.gbiome
    permission-message: You are not allowed to edit biomes.
    usage: |
      /<command> set <biometype> - Sets biometype of selection
      /<command> read - Gives list of biomes in selection
      /<command> biometypes - Lists all types

permissions:
  gbiome.gbiome:
    default: op
    description: Access to gBiome